<a href="https://colab.research.google.com/github/yashwantganesh/AI-Lab/blob/master/AI%20experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Experiment 1


1) different ways to create a numpy array

In [ ]:
import numpy as np
l=np.array([4,5,6])
print(l)

[4 5 6]


2)add,remove,modify array elements


In [ ]:
#add
l=np.array([2,3])
l=np.append(l,[4,5])
print(l)

[2 3 4 5]


In [ ]:
#remove
l=np.array([2,3,4,5])
l=np.delete(l,1)
print(l)

[2 4 5]


In [ ]:
#modify
l=np.array([2,3,4])
l[l<4]=1
print(l)

[1 1 4]


3)arthematic operations on numpy array



In [ ]:
import numpy as np
l=np.random.random((2,2))
j=np.random.random((2,2))
num_sum=np.add(l,j)
num_diff=np.subtract(l,j)
num_prod=np.multiply(l,j)
num_quo=np.divide(l,j)
num_mod=np.power(l,j)
num_pow=np.power(l,j)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)


[[1.72081078 0.98420744]
 [0.39528237 1.25190636]]
[[ 0.12241812 -0.56773221]
 [-0.18732683  0.51507073]]
[[0.73655089 0.1615861 ]
 [0.0302892  0.32549292]]
[[1.15317653 0.26835787]
 [0.35693831 2.3980614 ]]
[[0.93684536 0.29595282]
 [0.51716634 0.95538729]]
[[0.93684536 0.29595282]
 [0.51716634 0.95538729]]


4) slicing and iterating of numpy arrays slicing

In [ ]:
#slicing
import numpy as np
j=np.array([4,5,6,7,8,9])
print(j[1:4])

[5 6 7]


In [ ]:
#iterating
for x in j:
  print(j)

[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 5 6 7 8 9]


5) matrix operations on numpy arrays

In [ ]:
import numpy as np
l=np.array([[4,6],[4,6]])
j=np.array([[6,4],[6,4]])
print(np.add(l,j))
print(np.subtract(l,j))
print(np.divide(l,j))

[[10 10]
 [10 10]]
[[-2  2]
 [-2  2]]
[[0.66666667 1.5       ]
 [0.66666667 1.5       ]]
